### ISSUE TITLE
failing to merge PRs

### ISSUE THREAD

**Issue by chris48s** [reporanger/feedback#3]
We've got a number if PRs which we've tagged with "squash when passing" but aren't being merged e.g:
https://github.com/badges/shields/pull/5465
https://github.com/badges/shields/pull/5463
It looks like repo ranger is trying to process them (it is creating merge commits to update the branches) so it does seem to "know" is is supposed to merge the PRs but then I guess its then not able to actually merge them.

We haven't made any changes to our branch protection rules AFAIK and the repo-ranger app does have access to push to our master branch:

![Screenshot at 2020-08-30 15-42-10](https://user-images.githubusercontent.com/6025893/91662015-a8423180-ead7-11ea-958b-d1899e8580da.png)

If there's any extra debug info you need, let me know. Thanks

**Comment by mfix22** [comment]
@chris48s @PyvesB this was from a bug in the GitHub API. I thought it had been resolved, so I removed a patch locally, but looks like it hasn't. 

I have since reverted the change that removed my path and everything should be working as expected now.  Let me know if it hasn't.

If you could, please remove the "squash when passing" label and then add it back.

Thanks for your understanding!

**Comment by chris48s** [comment]
No probs. PRs are merging normally now. Thanks for the quick response.

**Comment by PyvesB** [comment]
Thanks for the quick resolution @mfix22 ! 👍🏻

**Comment by mfix22** [comment]
Thanks for using Ranger @PyvesB ! 💛
